# Create and start:
#   docker compose up -d

# View running:
#   docker ps
# View running and stopped:
#   docker ps --all
# Start the stopped container (e.g. after host reboot):
#   docker start mysql8

# Stop:
#   docker compose down
# Wipe volume:
#   docker volume rm mysql8data

services:
  mysql8:
    image: mysql:8.4-oraclelinux9
    container_name: mysql8
    volumes:
      - mysql8data:/var/lib/mysql
    networks:
      - sTest
    hostname: mysql8
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST_NAME: mysql8
      MYSQL_DATABASE: 'ushat'
      MYSQL_ROOT_PASSWORD: '999'
      MYSQL_USER: 'shsha'
      MYSQL_PASSWORD: '999'

networks:
  sTest:
    name: d-net1
    driver: bridge
volumes:
  mysql8data:
