spring.application.name=code

spring.profiles.active=dev

spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

management.endpoint.health.show-details=always
management.health.db.enabled=true
