spring.datasource.url=jdbc:mysql://${DB_HOST}/userData
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

logging.level.org.springframework=INFO
logging.level.com.project=DEBUG
logging.file.name=logs/app.log
