spring.application.name=code

spring.profiles.active = dev

# other values 'none' | `validate` | 'create' | 'create-drop'
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# see BROKEN,md
spring.jpa.properties.hibernate.current_session_context_class = thread

management.endpoint.health.show-details=always
management.health.db.enabled=true
