spring.application.name=code

spring.profiles.active=dev

spring.datasource.schema=classpath:schema.sql
spring.datasource.data=classpath:data.sql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoint.health.show-details=always
management.health.db.enabled=true
